"""initial: video frame transcript

Revision ID: 2a29294e34c3
Revises:
Create Date: 2026-06-10 18:47:52.400809

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a29294e34c3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("object_store_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_sha256"), "videos", ["sha256"], unique=True)
    op.create_index(op.f("ix_videos_status"), "videos", ["status"], unique=False)
    op.create_table(
        "frames",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("timestamp_ms", sa.Integer(), nullable=False),
        sa.Column("object_store_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_frames_video_id"), "frames", ["video_id"], unique=False)
    op.create_index("ix_frames_video_ts", "frames", ["video_id", "timestamp_ms"], unique=False)
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_segments_video_start", "transcript_segments", ["video_id", "start_ms"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_segments_video_id"), "transcript_segments", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcript_segments_video_id"), table_name="transcript_segments")
    op.drop_index("ix_segments_video_start", table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index("ix_frames_video_ts", table_name="frames")
    op.drop_index(op.f("ix_frames_video_id"), table_name="frames")
    op.drop_table("frames")
    op.drop_index(op.f("ix_videos_status"), table_name="videos")
    op.drop_index(op.f("ix_videos_sha256"), table_name="videos")
    op.drop_table("videos")
    # ### end Alembic commands ###
