"""phase2: detections and frame_captions

Revision ID: 8699c55f1bc4
Revises: 2a29294e34c3
Create Date: 2026-06-10 19:20:57.112230

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8699c55f1bc4"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "2a29294e34c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bbox_x1", sa.Integer(), nullable=False),
        sa.Column("bbox_y1", sa.Integer(), nullable=False),
        sa.Column("bbox_x2", sa.Integer(), nullable=False),
        sa.Column("bbox_y2", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_detections_label"), "detections", ["label"], unique=False)
    op.create_index(
        "ix_detections_video_frame", "detections", ["video_id", "frame_index"], unique=False
    )
    op.create_index(op.f("ix_detections_video_id"), "detections", ["video_id"], unique=False)
    op.create_table(
        "frame_captions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_captions_video_frame", "frame_captions", ["video_id", "frame_index"], unique=False
    )
    op.create_index(
        op.f("ix_frame_captions_video_id"), "frame_captions", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_frame_captions_video_id"), table_name="frame_captions")
    op.drop_index("ix_captions_video_frame", table_name="frame_captions")
    op.drop_table("frame_captions")
    op.drop_index(op.f("ix_detections_video_id"), table_name="detections")
    op.drop_index("ix_detections_video_frame", table_name="detections")
    op.drop_index(op.f("ix_detections_label"), table_name="detections")
    op.drop_table("detections")
    # ### end Alembic commands ###
